// <auto-generated />
using Lab6_Variant7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab6_Variant7.Migrations
{
    [DbContext(typeof(PlaceContext))]
    [Migration("20260220130910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Lab6_Variant7.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasDiscriminator<string>("PlaceType").HasValue("Place");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lab6_Variant7.Models.City", b =>
                {
                    b.HasBaseType("Lab6_Variant7.Models.Place");

                    b.Property<string>("Mayor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("RegionId");

                    b.HasDiscriminator().HasValue("City");
                });

            modelBuilder.Entity("Lab6_Variant7.Models.Region", b =>
                {
                    b.HasBaseType("Lab6_Variant7.Models.Place");

                    b.Property<string>("Leadership")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SettlementsCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Region");
                });

            modelBuilder.Entity("Lab6_Variant7.Models.Village", b =>
                {
                    b.HasBaseType("Lab6_Variant7.Models.Place");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Village");
                });

            modelBuilder.Entity("Lab6_Variant7.Models.City", b =>
                {
                    b.HasOne("Lab6_Variant7.Models.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Lab6_Variant7.Models.Region", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
